### ISSUE TITLE
winget

### ISSUE THREAD

**Issue by EEB7ADev** [EEB7ADev/EZDD#2]
Winget is used to install git, which is used to check for updates.
However, Winget does not appear to function when it's being run in a batch file.

the function of git for this program is to download the repository and then check the version.txt file for any differences. that's the only reason.

If you can tell me another way to do this, that would be greatly appreciated.

**Comment by EEB7ADev** [comment]
I have attempted a fix and compressed the files into prerelease 10.

If this fix succeeds it will become release 1

**Comment by a-catgirl-dev** [comment]
maybe ``cmd.exe -k winget <wget parameters>``? techinically it isn't being run from a batch file, but a new cmd.exe process.
if this doesn't work, try ``start cmd.exe -k winget <wget parameters>``, but you would have to write code to make sure git is installed

**i think before you do this, you should look into other methods of checking for updates, and try it on a system WITHOUT git installed**
